version: 0.2

phases:
  build:
    commands:
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 329981824160.dkr.ecr.ap-northeast-2.amazonaws.com
      - docker build -t my_web .
      - docker tag my_web:latest 329981824160.dkr.ecr.ap-northeast-2.amazonaws.com/my_web:latest
      - docker push 329981824160.dkr.ecr.ap-northeast-2.amazonaws.com/my_web:latest

      
      